# This is a basic workflow that is manually triggered

name: Desmos

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]


# This workflow makes a 64 bit Raspberry Pi Ubuntu Server Image.
# It does not have the security issues mentioned here: https://github.com/tendermint/tendermint/blob/master/docs/tendermint-core/running-in-production.md#validator-signing-on-32-bit-architectures-or-arm
# Later, more devices will be supported, as well.


jobs:
  build:
    name: Desmos Pi Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out imager
        uses: actions/checkout@v2

      - name: check out desmos
        uses: actions/checkout@v2
        with:
          repository: desmos-labs/desmos
          path: desmos/desmos
          ref: v0.10.0

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Compile
        run: |
          cd desmos/desmos
          make build
        env:
          GOOS: linux
          GOARCH: arm64
        
      - name: Upload Gaia Arm64 Binaries
        uses: actions/upload-artifact@v2
        with:
          name: desmos arm64
          path: desmos/desmos/build/

      - name: Build desmos.img
        run: docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build desmos/desmos.json

# Compression fails, disable it for now
#      - name: Install PiShrink
#        run: |
#          wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
#          chmod +x pishrink.sh
#          sudo mv pishrink.sh /usr/local/bin

#      - name: Shrink desmos.img
#        run: sudo pishrink.sh -a -Z -v -r desmos.img

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Desmos Image
          path: desmos.img

